// PRODUCT TYPE ACTIONS
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS' 
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'