// PRODUCT TYPE ACTIONS
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS' 
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'
export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'