// PRODUCT TYPE ACTIONS
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const ADD_PRODUCT_PENDING = 'ADD_PRODUCT_PENDING'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'
export const UPDATE_PRODUCT_PENDING = 'UPDATE_PRODUCT_PENDING'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR'
export const DELETE_PRODUCT_PENDING = 'DELETE_PRODUCT_PENDING'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'
export const SET_SELECTED_PRODUCT_ID = 'SET_SELECTED_PRODUCT_ID'
export const FILTER_PRODUCTS_BY_SIZE = 'FILTER_PRODUCTS_BY_SIZE'
export const ORDER_PRODUCTS_BY_PRICE = 'ORDER_PRODUCTS_BY_PRICE'
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY'

// CART TYPE ACTIONS
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const REMOVE_ALL_FROM_CART = 'REMOVE_ALL_FROM_CART'
export const CLEAR_CART = 'CLEAR_CART'

// USER TYPE ACTIONS
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'
export const ADD_USER_PENDING = 'ADD_USER_PENDING'
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS'
export const ADD_USER_ERROR = 'ADD_USER_ERROR'
export const USER_LOGOUT = 'USER_LOGOUT'
export const FETCH_USERS = 'FETCH_USERS'
export const IS_AUTH = 'IS_AUTH'

// CATEGORIE TYPE ACTIONS
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const ADD_CATEGORIE_PENDING = 'ADD_CATEGORIE_PENDING'
export const ADD_CATEGORIE_SUCCESS = 'ADD_CATEGORIE_SUCCESS'
export const ADD_CATEGORIE_ERROR = 'ADD_CATEGORIE_ERROR'
export const DELETE_CATEGORIE_PENDING = 'DELETE_CATEGORIE_PENDING'
export const DELETE_CATEGORIE_SUCCESS = 'DELETE_CATEGORIE_SUCCESS'
export const DELETE_CATEGORIE_ERROR = 'DELETE_CATEGORIE_ERROR'

// MERCADOPAGO TYPE ACTIONS
export const MERCADOPAGO_SUCCESS = 'MERCADOPAGO_SUCCESS'
export const MERCADOPAGO_PENDING = 'MERCADOPAGO_PENDING'
export const MERCADOPAGO_ERROR = 'MERCADOPAGO_ERROR'

//ORDER TYPE ACTIONS
export const POST_ORDER_FETCHING = 'POST_ORDER_FETCHING'
export const POST_ORDER_FULFILLED = 'POST_ORDER_FULFILLED'
export const POST_ORDER_REJECTED = 'POST_ORDER_REJECTED'

export const GET_ORDER_FETCHING = 'GET_ORDER_FETCHING'
export const GET_ORDER_FULFILLED = 'GET_ORDER_FULFILLED'
export const GET_ORDER_REJECTED = 'GET_ORDER_REJECTED'

export const ORDER_CANCEL_FETCHING = 'ORDER_CANCEL_FETCHING'
export const ORDER_CANCEL_FULFILLED = 'ORDER_CANCEL_FULFILLED'
export const ORDER_CANCEL_REJECTED = 'ORDER_CANCEL_REJECTED'